### ISSUE TITLE
Dedicated preview crash against ucrtbase.dll

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#11]
```
Faulting application name: LunaticVibesF.exe, version: 0.0.0.0, time stamp: 0x661020f8
Faulting module name: ucrtbase.dll, version: 10.0.20348.1, time stamp: 0xdacb234c
Exception code: 0xc0000409
Fault offset: 0x000000000007ca9e
Faulting process id: 0x79c
Faulting application start time: 0x01da87e1e886232a
Faulting application path: C:\Users\Administrator\Downloads\LR2 - HD (720p)\LR2 - HD (720p)\LR2beta3\LunaticVibesF.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 15bd7617-8fe8-4b1f-8551-2787f8e1a40d
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by BKVad1m** [comment]
When Direct Preview is disabled

**Comment by chown2** [comment]
> When Direct Preview is disabled

Reproduced, thanks

```


2024-04-06 13:03:49.223 DEBUG [4698] ["scene_select.cpp"@3059] [Select] Chart loaded -> PREVIEW_START_SAMPLE_LOADING
[Thread 0x7fffed0006c0 (LWP 4698) exited]

Thread 21 "MainThread" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffda0006c0 (LWP 4692)]
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;

..

Thread 21 (Thread 0x7fffda0006c0 (LWP 4692) "MainThread"):
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff6eab393 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff6e5a6c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff6e424b8 in __GI_abort () at abort.c:79
#4  0x000055555921dd3f in SceneSelect::updatePreview (this=0x52500000f110) at /path/to/lunaticvibesf/src/game/scene/scene_select.cpp:3173
#5  0x00005555591ccd15 in SceneSelect::_updateAsync (this=0x52500000f110) at /path/to/lunaticvibesf/src/game/scene/scene_select.cpp:842
#6  0x0000555558e20338 in SceneBase::_updateAsync1 (this=0x52500000f110) at /path/to/lunaticvibesf/src/game/scene/scene.cpp:271
#7  0x0000555558e701a8 in std::__invoke_impl<void, void (SceneBase::*&)(), SceneBase*&> (__f=@0x5030006770b0: (void (SceneBase::*)(class SceneBase * const)) 0x555558e2015e <SceneBase::_updateAsync1()>, __t=@0x5030006770c0: 0x52500000f110) at /usr/include/c++/13.2.1/bits/invoke.h:74
#8  0x0000555558e690e9 in std::__invoke<void (SceneBase::*&)(), SceneBase*&> (__fn=@0x5030006770b0: (void (SceneBase::*)(class SceneBase * const)) 0x555558e2015e <SceneBase::_updateAsync1()>) at /usr/include/c++/13.2.1/bits/invoke.h:96
#9  0x0000555558e627cd in std::_Bind<void (SceneBase::*(SceneBase*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x5030006770b0, __args=...) at /usr/include/c++/13.2.1/functional:506
#10 0x0000555558e5974f in std::_Bind<void (SceneBase::*(SceneBase*))()>::operator()<, void>() (this=0x5030006770b0) at /usr/include/c++/13.2.1/functional:591
#11 0x0000555558e5032b in std::__invoke_impl<void, std::_Bind<void (SceneBase::*(SceneBase*))()>&>(std::__invoke_other, std::_Bind<void (SceneBase::*(SceneBase*))()>&) (__f=...) at /usr/include/c++/13.2.1/bits/invoke.h:61
#12 0x0000555558e43822 in std::__invoke_r<void, std::_Bind<void (SceneBase::*(SceneBase*))()>&>(std::_Bind<void (SceneBase::*(SceneBase*))()>&) (__fn=...) at /usr/include/c++/13.2.1/bits/invoke.h:111
#13 0x0000555558e3b268 in std::_Function_handler<void (), std::_Bind<void (SceneBase::*(SceneBase*))()> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/13.2.1/bits/std_function.h:290
#14 0x0000555558d059bb in std::function<void ()>::operator()() const (this=0x52500000f150) at /usr/include/c++/13.2.1/bits/std_function.h:591
#15 0x0000555559eb4ccc in AsyncLooper::run (this=0x52500000f110) at /path/to/lunaticvibesf/src/common/asynclooper.cpp:65
#16 0x0000555559eb53f0 in AsyncLooper::_loopWithSleep (this=0x52500000f110) at /path/to/lunaticvibesf/src/common/asynclooper.cpp:185
#17 0x0000555559eb7e15 in std::__invoke_impl<void, void (AsyncLooper::*)(), AsyncLooper*> (__f=@0x5030006e8e20: (void (AsyncLooper::*)(class AsyncLooper * const)) 0x555559eb4fb0 <AsyncLooper::_loopWithSleep()>, __t=@0x5030006e8e18: 0x52500000f110) at /usr/include/c++/13.2.1/bits/invoke.h:74
#18 0x0000555559eb792d in std::__invoke<void (AsyncLooper::*)(), AsyncLooper*> (__fn=@0x5030006e8e20: (void (AsyncLooper::*)(class AsyncLooper * const)) 0x555559eb4fb0 <AsyncLooper::_loopWithSleep()>) at /usr/include/c++/13.2.1/bits/invoke.h:96
#19 0x0000555559eb76d4 in std::thread::_Invoker<std::tuple<void (AsyncLooper::*)(), AsyncLooper*> >::_M_invoke<0ul, 1ul> (this=0x5030006e8e18) at /usr/include/c++/13.2.1/bits/std_thread.h:292
#20 0x0000555559eb7554 in std::thread::_Invoker<std::tuple<void (AsyncLooper::*)(), AsyncLooper*> >::operator() (this=0x5030006e8e18) at /usr/include/c++/13.2.1/bits/std_thread.h:299
#21 0x0000555559eb750c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (AsyncLooper::*)(), AsyncLooper*> > >::_M_run (this=0x5030006e8e10) at /usr/include/c++/13.2.1/bits/std_thread.h:244
#22 0x00007ffff70e1943 in std::execute_native_thread_routine (__p=0x5030006e8e10) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
#23 0x00007ffff6ea955a in start_thread (arg=<optimized out>) at pthread_create.c:447
#24 0x00007ffff6f26a3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by chown2** [comment]
Will be fixed in the next release, thanks. Until then, you can enable "Direct preview".
