### ISSUE TITLE
Access to PlayContextParams is not synchronized between threads

### ISSUE THREAD

**Issue by chown2** [chown2/lunaticvibesf#25]
Easily reproducible with this skin: https://github.com/Vad1mCSO2/BlackKnightMania_for_LV

Maybe related: #15.

```
    #0 0x7927f905a2ce in __interceptor_memmove /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:882
    #1 0x5877e9eb055b in double* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<double const, double>(double const*, double const*, double*) /usr/include/c++/13.2.1/bits/stl_algobase.h:437
    #2 0x5877e9eb03e9 in double* std::__copy_move_a2<false, double const*, double*>(double const*, double const*, double*) /usr/include/c++/13.2.1/bits/stl_algobase.h:506
    #3 0x5877e9eb02b7 in double* std::__copy_move_a1<false, double const*, double*>(double const*, double const*, double*) /usr/include/c++/13.2.1/bits/stl_algobase.h:533
    #4 0x5877e9eaff17 in double* std::__copy_move_a<false, __gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, double*>(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, double*) /usr/include/c++/13.2.1/bits/stl_algobase.h:540
    #5 0x5877e9eaf407 in double* std::copy<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, double*>(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, double*) /usr/include/c++/13.2.1/bits/stl_algobase.h:633
    #6 0x5877e9eae822 in double* std::__uninitialized_copy<true>::__uninit_copy<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, double*>(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, double*) /usr/include/c++/13.2.1/bits/stl_uninitialized.h:147
    #7 0x5877e9eadea5 in double* std::uninitialized_copy<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, double*>(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, double*) /usr/include/c++/13.2.1/bits/stl_uninitialized.h:185
    #8 0x5877e9eab6ed in double* std::__uninitialized_copy_a<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, double*, double>(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, double*, std::allocator<double>&) /usr/include/c++/13.2.1/bits/stl_uninitialized.h:373
    #9 0x5877e9ea81a0 in std::vector<double, std::allocator<double> >::vector(std::vector<double, std::allocator<double> > const&) /usr/include/c++/13.2.1/bits/stl_vector.h:603
    #10 0x5877e9e9e131 in SpriteLine::updateRects() /path/to/lunaticvibesf/src/game/graphics/sprite_graph.cpp:238
    #11 0x5877e9ea04a6 in SpriteLine::update(lunaticvibes::Time const&) /path/to/lunaticvibesf/src/game/graphics/sprite_graph.cpp:298
    #12 0x5877e98c0597 in operator() /path/to/lunaticvibesf/src/game/skin/skin.cpp:55
    #13 0x5877e98c8b9f in for_each<std::_List_iterator<std::shared_ptr<SpriteBase> >, SkinBase::update()::<lambda(const std::shared_ptr<SpriteBase>&)> > /usr/include/c++/13.2.1/bits/stl_algo.h:3833
    #14 0x5877e98c7dea in __brick_walk1<std::_List_iterator<std::shared_ptr<SpriteBase> >, SkinBase::update()::<lambda(const std::shared_ptr<SpriteBase>&)> > /usr/include/c++/13.2.1/pstl/algorithm_impl.h:94
    #15 0x5877e98c7732 in __pattern_walk1<const __pstl::execution::v1::parallel_unsequenced_policy&, std::_List_iterator<std::shared_ptr<SpriteBase> >, SkinBase::update()::<lambda(const std::shared_ptr<SpriteBase>&)>, std::integral_constant<bool, false> > /usr/include/c++/13.2.1/pstl/algorithm_impl.h:111
    #16 0x5877e98c6cb1 in for_each<const __pstl::execution::v1::parallel_unsequenced_policy&, std::_List_iterator<std::shared_ptr<SpriteBase> >, SkinBase::update()::<lambda(const std::shared_ptr<SpriteBase>&)> > /usr/include/c++/13.2.1/pstl/glue_algorithm_impl.h:59
    #17 0x5877e98c0cea in SkinBase::update() /path/to/lunaticvibesf/src/game/skin/skin.cpp:58
    #18 0x5877e99a248f in SkinLR2::update() /path/to/lunaticvibesf/src/game/skin/skin_lr2.cpp:4317
    #19 0x5877e9331232 in SceneBase::update() /path/to/lunaticvibesf/src/game/scene/scene.cpp:132
    #20 0x5877e9197c1c in mainLoop() /path/to/lunaticvibesf/src/game/game.cpp:392
    #21 0x5877e91951a0 in main /path/to/lunaticvibesf/src/game/game.cpp:279
    #22 0x7927f8643ccf  (/usr/lib/libc.so.6+0x25ccf) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #23 0x7927f8643d89 in __libc_start_main (/usr/lib/libc.so.6+0x25d89) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #24 0x5877e918d024 in _start (/path/to/lunaticvibesf/build/bin/Debug/LunaticVibesF+0x374a024) (BuildId: ad0e7416a2d0b289a6b81dd4cdb561b34ced33c5)

0x512000e00270 is located 0 bytes after 304-byte region [0x512000e00140,0x512000e00270)
allocated by thread T0 (MainThread) here:
    #0 0x7927f90e2002 in operator new(unsigned long) /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x5877e943282c in std::__new_allocator<double>::allocate(unsigned long, void const*) /usr/include/c++/13.2.1/bits/new_allocator.h:147
    #2 0x5877e9420fed in std::allocator_traits<std::allocator<double> >::allocate(std::allocator<double>&, unsigned long) /usr/include/c++/13.2.1/bits/alloc_traits.h:482
    #3 0x5877e9420fed in std::_Vector_base<double, std::allocator<double> >::_M_allocate(unsigned long) /usr/include/c++/13.2.1/bits/stl_vector.h:378
    #4 0x5877e9eadb1b in std::_Vector_base<double, std::allocator<double> >::_M_create_storage(unsigned long) /usr/include/c++/13.2.1/bits/stl_vector.h:395
    #5 0x5877e9eab1ec in std::_Vector_base<double, std::allocator<double> >::_Vector_base(unsigned long, std::allocator<double> const&) /usr/include/c++/13.2.1/bits/stl_vector.h:332
    #6 0x5877e9ea801a in std::vector<double, std::allocator<double> >::vector(std::vector<double, std::allocator<double> > const&) /usr/include/c++/13.2.1/bits/stl_vector.h:600
    #7 0x5877e9e9e131 in SpriteLine::updateRects() /path/to/lunaticvibesf/src/game/graphics/sprite_graph.cpp:238
    #8 0x5877e9ea04a6 in SpriteLine::update(lunaticvibes::Time const&) /path/to/lunaticvibesf/src/game/graphics/sprite_graph.cpp:298
    #9 0x5877e98c0597 in operator() /path/to/lunaticvibesf/src/game/skin/skin.cpp:55
    #10 0x5877e98c8b9f in for_each<std::_List_iterator<std::shared_ptr<SpriteBase> >, SkinBase::update()::<lambda(const std::shared_ptr<SpriteBase>&)> > /usr/include/c++/13.2.1/bits/stl_algo.h:3833
    #11 0x5877e98c7dea in __brick_walk1<std::_List_iterator<std::shared_ptr<SpriteBase> >, SkinBase::update()::<lambda(const std::shared_ptr<SpriteBase>&)> > /usr/include/c++/13.2.1/pstl/algorithm_impl.h:94
    #12 0x5877e98c7732 in __pattern_walk1<const __pstl::execution::v1::parallel_unsequenced_policy&, std::_List_iterator<std::shared_ptr<SpriteBase> >, SkinBase::update()::<lambda(const std::shared_ptr<SpriteBase>&)>, std::integral_constant<bool, false> > /usr/include/c++/13.2.1/pstl/algorithm_impl.h:111
    #13 0x5877e98c6cb1 in for_each<const __pstl::execution::v1::parallel_unsequenced_policy&, std::_List_iterator<std::shared_ptr<SpriteBase> >, SkinBase::update()::<lambda(const std::shared_ptr<SpriteBase>&)> > /usr/include/c++/13.2.1/pstl/glue_algorithm_impl.h:59
    #14 0x5877e98c0cea in SkinBase::update() /path/to/lunaticvibesf/src/game/skin/skin.cpp:58
    #15 0x5877e99a248f in SkinLR2::update() /path/to/lunaticvibesf/src/game/skin/skin_lr2.cpp:4317
    #16 0x5877e9331232 in SceneBase::update() /path/to/lunaticvibesf/src/game/scene/scene.cpp:132
    #17 0x5877e9197c1c in mainLoop() /path/to/lunaticvibesf/src/game/game.cpp:392
    #18 0x5877e91951a0 in main /path/to/lunaticvibesf/src/game/game.cpp:279
    #19 0x7927f8643ccf  (/usr/lib/libc.so.6+0x25ccf) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:882 in __interceptor_memmove
Shadow bytes around the buggy address:
  0x512000dfff80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x512000e00000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x512000e00080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x512000e00100: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x512000e00180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x512000e00200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00[fa]fa
  0x512000e00280: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x512000e00300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x512000e00380: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa fa
  0x512000e00400: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x512000e00480: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==157045==ABORTING
```

(pay attention to 'for_each .. parallel_unsequenced_policy')

**Comment by BKVad1m** [comment]
My play skin is being updated
